# @package solver
_target_: solvers.fv.solver.FVSolver
name: fv

# Common parameters (inherited from root config)
Re: ${Re}
lid_velocity: ${lid_velocity}
Lx: ${Lx}
Ly: ${Ly}
nx: ${N}
ny: ${N}
max_iterations: ${max_iterations}
tolerance: ${tolerance}

# FV-specific parameters
convection_scheme: Upwind
limiter: MUSCL
alpha_uv: 0.6        # velocity under-relaxation
alpha_p: 0.4         # pressure under-relaxation
linear_solver_tol: 1.0e-6  # SciPy linear solver tolerance
