# @package solver
# Single Grid Spectral Solver (no multigrid acceleration)
_target_: solvers.spectral.sg.SGSolver
name: spectral

# Problem parameters (interpolated from root config)
Re: ${Re}
lid_velocity: ${lid_velocity}
Lx: ${Lx}
Ly: ${Ly}
nx: ${N}
ny: ${N}

# Solver control
tolerance: ${tolerance}
max_iterations: ${max_iterations}

# Spectral-specific parameters
basis_type: chebyshev    # "chebyshev" or "legendre"
CFL: 2.5
beta_squared: 5.0        # artificial compressibility parameter

# Corner singularity treatment
# Options: "smoothing" or "saad"/"polynomial"
corner_treatment: smoothing
corner_smoothing: 0.15   # smoothing width (fraction of domain) for smoothing method

# No multigrid for single grid solver
multigrid: none
