# @package solver
# V-cycle MultiGrid (VMG) Spectral Solver with multigrid acceleration

defaults:
  - /solver/spectral/sg  # Extend single grid spectral solver using absolute path

_target_: solvers.spectral.vmg.VMGSolver

# Override name for VMG variant
name: spectral_vmg

# VMG Multigrid settings
multigrid: vmg
n_levels: 3
coarse_tolerance_factor: 1.0
prolongation_method: fft
restriction_method: fft
