# @package solver
# V-cycle MultiGrid (VMG) Spectral Solver with multigrid acceleration
#
# Uses FAS (Full Approximation Storage) scheme for nonlinear NS equations.
# Notation from Zhang & Xi (2010): 48-VMG-123 means:
#   - N=48 on finest, 3 levels (48→24→12)
#   - Pre-smoothing: 1 step on finest, 2 on intermediate, 3 on coarsest

defaults:
  - /solver/spectral/sg  # Extend single grid spectral solver using absolute path

_target_: solvers.spectral.vmg.VMGSolver

# Override name for VMG variant
name: spectral_vmg

# VMG Multigrid settings
multigrid: vmg
n_levels: 3

# Smoothing iterations per level (coarse-to-fine order: [coarsest, ..., finest])
# Paper default is 1-2-3 from fine to coarse, so [3, 2, 1] in our ordering
pre_smoothing: [3, 2, 1]
post_smoothing: null  # No post-smoothing by default (paper says often unnecessary)

# Transfer operators (Zhang & Xi 2010 paper method)
# FFT/DCT for spectral accuracy in both prolongation and restriction
# Restriction for solutions uses injection (hardcoded in fsg.py - FAS requirement)
# Restriction for residuals uses this setting
prolongation_method: fft
restriction_method: fft

# Coarse grid correction damping (0 = no correction, 1 = full correction)
# With proper FAS tau correction, use full correction (1.0)
correction_damping: 1.0
