# @package solver
# V-cycle Multigrid (VMG) Spectral Solver
#
# Implements proper V-cycle multigrid with Full Approximation Storage (FAS).
# Achieves ~2.8x speedup vs single grid with default parameters.
#
# Uses recursive coarse grid correction with damped prolongation.

defaults:
  - /solver/spectral/sg  # Extend single grid spectral solver

_target_: solvers.spectral.vmg.VMGSolver

# Override name for VMG variant
name: spectral_vmg

# VMG Multigrid settings
multigrid: vmg
n_levels: 10           # Max levels (actual levels limited by coarsest_n)
coarsest_n: 12         # Minimum N for coarsest grid (must resolve physics)

# Transfer operators
prolongation_method: fft
restriction_method: fft

# V-cycle parameters (tested optimal values)
pre_smooth: 5    # Pre-smoothing steps per level
post_smooth: 5   # Post-smoothing steps per level
damping: 0.5    # Damping factor for coarse grid correction
