# @package solver
# V-cycle MultiGrid (VMG) Spectral Solver with multigrid acceleration
#
# Uses FAS (Full Approximation Storage) scheme for nonlinear NS equations.
# Notation from Zhang & Xi (2010): 48-VMG-123 means:
#   - N=48 on finest, 3 levels (48→24→12)
#   - Pre-smoothing: 1 step on finest, 2 on intermediate, 3 on coarsest
#
# KNOWN LIMITATIONS:
# The FAS coarse grid correction is partially misaligned with RK4 pseudo-time stepping:
#
# 1. COARSE SMOOTHING WORKS: Modified residual |R + tau| decreases correctly
#    (from 100 to ~22 with 10 smoothing steps)
#
# 2. CORRECTION APPLICATION FAILS: When the correction delta = u_coarse - u_restricted
#    is prolongated and applied to fine grid, it makes the fine residual WORSE:
#    - Full correction (damping=1.0): fine residual increases 44%
#    - damping=0.5: roughly neutral
#    - damping=0.25: modest improvement (8%)
#
# The issue is that the coarse grid correction direction doesn't align well with
# the fine grid error when using spectral discretization + RK4 pseudo-time stepping.
# The error dynamics are resolution-dependent in this nonlinear system.
#
# Zhang & Xi (2010) may use different smoothers or correction strategies.
# Their reported 26x speedup suggests fundamentally different treatment.
#
# RECOMMENDATION: Use FSG (Full Single Grid) instead - it provides 2x speedup
# without the problematic FAS correction. VMG is provided for experimentation only.

defaults:
  - /solver/spectral/sg  # Extend single grid spectral solver using absolute path

_target_: solvers.spectral.vmg.VMGSolver

# Override name for VMG variant
name: spectral_vmg

# VMG Multigrid settings
multigrid: vmg
n_levels: 2  # 2 levels is more stable than 3 for VMG

# Smoothing iterations per level (coarse-to-fine order: [coarsest, ..., finest])
# More smoothing on coarse levels since the FAS tau correction overhead is highest there
pre_smoothing: [5, 2]
post_smoothing: null  # No post-smoothing (paper says often unnecessary)

# Transfer operators (Zhang & Xi 2010 paper method)
# FFT/DCT for spectral accuracy in both prolongation and restriction
# Restriction for solutions uses injection (hardcoded in fsg.py - FAS requirement)
# Restriction for residuals uses this setting
prolongation_method: fft
restriction_method: fft

# Coarse grid correction damping (0 = no correction, 1 = full correction)
# Damped correction (0.5) is required for stability with spectral methods
# Higher values cause oscillation and divergence
correction_damping: 0.5

# Note: CFL is automatically reduced on coarser levels (halved per level)
# This improves stability when the FAS tau correction is applied
