# @package solver
_target_: solvers.fv.solver.FVSolver
name: fv

# Problem parameters (interpolated from root config)
Re: ${Re}
lid_velocity: ${lid_velocity}
Lx: ${Lx}
Ly: ${Ly}
nx: ${N}
ny: ${N}

# Solver control
tolerance: ${tolerance}
max_iterations: ${max_iterations}

# FV-specific parameters
convection_scheme: TVD
limiter: MUSCL
alpha_uv: 0.4        # velocity under-relaxation
alpha_p: 0.2         # pressure under-relaxation
linear_solver_tol: 1.0e-9

# Corner singularity treatment
# Options: "none", "smoothing", or "saad"/"polynomial"
corner_treatment: none
corner_smoothing: 0.15   # smoothing width for "smoothing" method
