# @package hydra.sweeper
#
# Optuna Sweeper Configuration for corner_smoothing optimization
# Usage: python main.py -m hydra/sweeper=optuna_corner
#
# For parallel execution, set n_jobs > 1 (requires storage to be set)
# Example: hydra.sweeper.n_jobs=4 hydra.sweeper.storage="sqlite:///optuna.db"

_target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

defaults:
  - sampler: tpe

# Optimization direction (minimize L2 error)
direction: minimize

# Study configuration
study_name: corner_smoothing_optimization
storage: null  # Set to "sqlite:///optuna.db" for parallel execution

# Number of trials and parallel jobs
n_trials: 15
n_jobs: 1  # Set > 1 for parallel trials (requires storage)

# Required fields
search_space: null
custom_search_space: null
params: null
